# Generated by Django 5.2.3 on 2025-07-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_stripe_payment_intend_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='heleket_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('heleket', 'Heleket')], max_length=20, null=True),
        ),
    ]
